### ISSUE TITLE
Cleanup README.md

### ISSUE THREAD

**Issue by d4rkd0s** [Mingosio/celebrity-picture-rater#4]
The README seems to be some basic Ruby README.md

This issue can be put off until the app is in a more running condition. Whenever you feel fit/best @pachonk  slap some kinda basic README for the project together. Tyty 🙏

**Comment by pachonk** [comment]
Lol, I wouldn't leave this readme bare....

**Comment by d4rkd0s** [comment]
@pachonk I have README.md improvements on the `community` branch. Can you update the requirements section.
